### ISSUE TITLE
Doesn't work with final releases of Xcode 8 and Swift 3

### ISSUE THREAD

**Issue by nebiros** [michael-yuji/MessagePack#5] opened 2016-09-19 20:51 UTC

**Comment by michael-yuji** [comment] 2016-09-19 21:40
Hi, the cocoapod version is pointing to swift 2.2, pull the master branch should work

**Comment by michael-yuji** [comment] 2016-09-19 21:42
It turns out there's indeed some problem, give me 5 mins to fix it.

**Comment by michael-yuji** [comment] 2016-09-19 21:49
The problem is due to Data.length is renamed to Data.count in Foundation. Fixed now

**Closed as completed by michael-yuji** 2016-09-19 21:49 UTC

**Comment by nebiros** [comment] 2016-09-19 22:36
Could you please push the latest tag to the cocoapod's trunk?. Thank you!

**Comment by nebiros** [comment] 2016-09-19 22:52
Also, I try using the repo url, but Xcode still complains about it:

```
Swift Compiler Error Group
YSMessagePack/Sources/operators.swift:11:18: Expected '{' after operator name in 'operator' declaration
YSMessagePack/Sources/operators.swift:12:19: Expected '{' after operator name in 'operator' declaration
YSMessagePack/Sources/operators.swift:25:23: 'inout' must appear before the parameter name
YSMessagePack/Sources/operators.swift:31:24: 'inout' must appear before the parameter name
YSMessagePack/Sources/pack.swift:48:61: 'inout' must appear before the parameter name
YSMessagePack/Sources/parse.swift:29:123: 'inout' must appear before the parameter name
YSMessagePack/Sources/unpack.swift:78:91: 'inout' must appear before the parameter name
YSMessagePack/Sources/unpack.swift:98:89: 'inout' must appear before the parameter name
YSMessagePack/Sources/unpack.swift:125:65: Expected type
YSMessagePack/Sources/unpack.swift:125:65: Expected ',' separator
YSMessagePack/Sources/unpack.swift:150:150: 'inout' must appear before the parameter name
YSMessagePack/Sources/unpack.swift:366:114: Unknown attribute 'escaping'
YSMessagePack/Sources/unpack.swift:366:159: Expected type
YSMessagePack/Sources/unpack.swift:366:159: Expected ',' separator
YSMessagePack/Sources/unpack.swift:389:107: Unknown attribute 'escaping'
YSMessagePack/Sources/misc.swift:129:27: Use of undeclared type 'Error'
YSMessagePack/Sources/misc.swift:135:29: Use of undeclared type 'Error'
YSMessagePack/Sources/misc.swift:129:13: Type 'PackingError' does not conform to protocol 'RawRepresentable'
YSMessagePack/Sources/misc.swift:135:13: Type 'UnpackingError' does not conform to protocol 'RawRepresentable'
YSMessagePack/Sources/misc.swift:194:34: Thrown expression type 'UnpackingError' does not conform to 'ErrorType'
YSMessagePack/Sources/NSDataCasters.swift:79:53: 'Encoding' is not a member type of 'String'
YSMessagePack/Sources/NSDataCasters.swift:90:58: 'Encoding' is not a member type of 'String'
YSMessagePack/Sources/NSDataCasters.swift:42:43: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/NSDataCasters.swift:49:43: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/NSDataCasters.swift:56:43: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/NSDataCasters.swift:63:46: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/NSDataCasters.swift:70:46: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/NSDataCasters.swift:85:61: Use of unresolved identifier 'Data'
YSMessagePack/Sources/NSDataCasters.swift:96:56: Use of unresolved identifier 'Data'
YSMessagePack/Sources/NSDataCasters.swift:100:21: Value of type 'UnsafePointer<Void>' (aka 'UnsafePointer<()>') has no member 'assumingMemoryBound'
YSMessagePack/Sources/NSDataCasters.swift:110:43: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/operators.swift:15:13: Operator implementation without matching operator declaration
YSMessagePack/Sources/operators.swift:25:13: Operator implementation without matching operator declaration
YSMessagePack/Sources/operators.swift:21:13: Operator implementation without matching operator declaration
YSMessagePack/Sources/operators.swift:31:13: Operator implementation without matching operator declaration
YSMessagePack/Sources/operators.swift:17:5: Value of type 'NSMutableData' has no member 'append'
YSMessagePack/Sources/operators.swift:22:5: Value of type 'NSMutableData' has no member 'append'
YSMessagePack/Sources/operators.swift:27:5: Value of type 'NSMutableData' has no member 'append'
YSMessagePack/Sources/operators.swift:33:5: Value of type 'NSMutableData' has no member 'append'
YSMessagePack/Sources/operators.swift:34:9: Cannot assign to value: 'lhs' is a 'let' constant
YSMessagePack/Sources/pack.swift:157:45: 'Encoding' is not a member type of 'StringLiteralType' (aka 'String')
YSMessagePack/Sources/pack.swift:40:13: Extraneous argument label 'item:' in call
YSMessagePack/Sources/pack.swift:51:19: Left side of mutating operator isn't mutable: 'byteArray' is a 'let' constant
YSMessagePack/Sources/pack.swift:60:42: Cannot pass immutable value as inout argument: 'byteArray' is a 'let' constant
YSMessagePack/Sources/pack.swift:66:30: 'Encoding' is not a member type of 'String'
YSMessagePack/Sources/pack.swift:87:19: Left side of mutating operator isn't mutable: 'byteArray' is a 'let' constant
YSMessagePack/Sources/pack.swift:91:19: Left side of mutating operator isn't mutable: 'byteArray' is a 'let' constant
YSMessagePack/Sources/pack.swift:94:19: Left side of mutating operator isn't mutable: 'byteArray' is a 'let' constant
YSMessagePack/Sources/pack.swift:97:19: Left side of mutating operator isn't mutable: 'byteArray' is a 'let' constant
YSMessagePack/Sources/pack.swift:100:19: Left side of mutating operator isn't mutable: 'byteArray' is a 'let' constant
YSMessagePack/Sources/pack.swift:103:19: Left side of mutating operator isn't mutable: 'byteArray' is a 'let' constant
YSMessagePack/Sources/pack.swift:106:19: Left side of mutating operator isn't mutable: 'byteArray' is a 'let' constant
YSMessagePack/Sources/pack.swift:109:19: Left side of mutating operator isn't mutable: 'byteArray' is a 'let' constant
YSMessagePack/Sources/pack.swift:162:35: Use of unresolved identifier 'repeatElement'
YSMessagePack/Sources/pack.swift:186:45: Thrown expression type 'PackingError' does not conform to 'ErrorType'
YSMessagePack/Sources/pack.swift:192:32: Thrown expression type 'PackingError' does not conform to 'ErrorType'
YSMessagePack/Sources/pack.swift:264:50: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/pack.swift:491:13: Argument labels '(item:, appendToBytes:)' do not match any available overloads
YSMessagePack/Sources/pack.swift:492:13: Argument labels '(item:, appendToBytes:)' do not match any available overloads
YSMessagePack/Sources/pack.swift:545:13: Argument labels '(item:, appendToBytes:)' do not match any available overloads
YSMessagePack/Sources/pack.swift:547:13: Argument labels '(item:, appendToBytes:)' do not match any available overloads
YSMessagePack/Sources/pack.swift:594:13: Argument labels '(item:, appendToBytes:)' do not match any available overloads
YSMessagePack/Sources/pack.swift:646:13: Argument labels '(item:, appendToBytes:)' do not match any available overloads
YSMessagePack/Sources/parse.swift:15:93: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/parse.swift:24:97: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/parse.swift:45:77: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/parse.swift:46:77: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/parse.swift:47:77: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/parse.swift:145:39: Thrown expression type 'UnpackingError' does not conform to 'ErrorType'
YSMessagePack/Sources/parse.swift:159:38: Thrown expression type 'UnpackingError' does not conform to 'ErrorType'
YSMessagePack/Sources/unpack.swift:23:123: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/unpack.swift:37:126: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/unpack.swift:60:134: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/unpack.swift:82:9: Value of type 'ByteArray' (aka 'Array<UInt8>') has no member 'removeSubrange'
YSMessagePack/Sources/unpack.swift:84:146: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/unpack.swift:104:9: Value of type 'ByteArray' (aka 'Array<UInt8>') has no member 'removeSubrange'
YSMessagePack/Sources/unpack.swift:106:150: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/unpack.swift:112:18: 'stride(from:to:by:)' is unavailable: call the 'stride(to:by:)' method instead
YSMessagePack/Sources/unpack.swift:139:150: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/unpack.swift:170:78: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/unpack.swift:171:78: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/unpack.swift:172:78: Use of unresolved identifier 'MemoryLayout'
YSMessagePack/Sources/unpack.swift:284:117: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/unpack.swift:291:117: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/unpack.swift:305:115: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/unpack.swift:311:115: '&' used with non-inout argument of type 'Int'
YSMessagePack/Sources/unpack.swift:314:43: Thrown expression type 'UnpackingError' does not conform to 'ErrorType'
YSMessagePack/Sources/unpack.swift:353:42: Thrown expression type 'UnpackingError' does not conform to 'ErrorType'
YSMessagePack/Sources/unpack.swift:359:13: Cannot assign to value: 'len' is a 'let' constant
YSMessagePack/Sources/unpack.swift:368:21: Use of unresolved identifier 'DispatchQueue'
YSMessagePack/Sources/unpack.swift:391:9: Use of unresolved identifier 'DispatchQueue'
YSMessagePack/Sources/unpack.swift:199:52: Thrown expression type 'PackingError' does not conform to 'ErrorType'
```

**Comment by michael-yuji** [comment] 2016-09-19 23:45
It looks like you are using swift2.3 (By seeing "unresolved identifier 'MemoryLayout'"), or either cocoa pod is porting it as swift2.3.
I really want to push to cocoapods' trunk. But so far I'm experiencing problem that I cannot install cocoapod on my MacBook Air after updated to Sierra. I'll do it ASAP sorry about that.

**Comment by michael-yuji** [comment] 2016-09-20 07:52
@nebiros  After hours and hours fighting with cocoapods, the cocoapods is finally synchronized with GitHub tag, point YSMessagePack to tag 1.6.2 should work now.
